### PR TITLE
Fix smoke tests running against Chrome 65.

### PR DESCRIPTION
**Pull request by samiwel**
### Description
This PR is an attempt to fix the broken concourse build by increasing the version of selenium chrome driver used by Chimp.

We observed that the smoke tests were running fine locally when pointing at staging environment which points towards a mismatch of chrome headless version (65.0.3325.146-1) and the selenium chrome driver version being used during the Concourse deploy staging job.

### How to test this PR.
The concourse pipeline should pass.

See link below for more information.
https://stackoverflow.com/questions/49162667/unknown-error-call-function-result-missing-value-for-selenium-send-keys-even

### CODE REVIEW

**Comment by samiwel** [comment]
@jonnyshaw89 Which version of chrome are you running locally?

**Comment by jonnyshaw89** [comment]
im running within the container `onsdigital/eq-author-build` which is the same way that concourse runs it

**Comment by samiwel** [comment]
I think the version of chimp may also need to be increased. Will investigate further later on.

**Comment by jonnyshaw89** [comment]
@samiwel @shahi645 The following command will checkout this branch and run it against staging within the container
`docker run -it onsdigital/eq-author-build bash -c "git clone https://github.com/ONSdigital/eq-smoke-tests.git; cd eq-smoke-tests/; git checkout fix-broken-smoketests-staging-env; yarn install; BASE_URL=https://staging-author.dev.eq.ons.digital yarn test_headless"`

**Comment by samiwel** [comment]
There are open issues on Selenium (see issue 5576) and Chromedriver (https://bugs.chromium.org/p/chromedriver/issues/list?can=2&q=2.36&sort=-id&colspec=ID+Status+Pri+Owner+Summary&cells=ids) open source projects. We should continue to uses Chrome 64 until issues with chromedriver 2.36 are resolved.

**Comment by shahi645** [comment]
@samiwel Should we close this PR until ongoing issues related to chromedriver are resolved?

**Comment by jonnyshaw89** [comment]
@shahi645 @samiwel We need to create some kind of reminder for us not to forget to un-pin the chrome version

**Comment by shahi645** [comment]
trello card ?

**Comment by jonnyshaw89** [comment]
@samiwel still an error since latest change
```
1) eQ Services Smoke Test
       should update navigation title when section title changed:
     Error: An element could not be located on the page using the given search parameters ("[data-testid='txt-section-title']").
```

**Comment by shahi645** [comment]
@samiwel Smoke tests are failing currently on section titles, which needs to be updated, then we can look at this again?

**Comment by hamishtaplin** [comment]
@shahi645 Working on this now as we've moved where you edit sections so it's all broken

**Comment by nealedj** [comment]
Chimp and chrome driver were both updated in https://github.com/ONSdigital/eq-smoke-tests/pull/14. Smoke tests pass locally and on CI so I think this PR has been superseded.

**Pull request closed without merging**
