### PR TITLE
Update selector for currency input fields

### PR DESCRIPTION
**Pull request by adammahmood**
### What is the context of this PR?
Updates the selector for currency fields so Cypress can validate the field exists.  

### How to review 
- Ensure test pass

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
Do we know what caused this change?

**Comment by adammahmood** [comment]
@jonnyshaw89 Unsure.  I tried having a quick look at recent commits in `eq-survey-runner` but couldn't find the cause.  Maybe someone more familiar with the codebase could have a look?

**Comment by adammahmood** [comment]
Caused by: https://github.com/ONSdigital/eq-survey-runner/pull/1922

**Comment by bitdivision** [comment]
This change has now been reverted in runner. 

It was originally caused by numeric input fields being changed to `<input type='number'>` rather than `type='text'`.

All inputs have now been reverted to `type='text'` due to strange cross browser behaviour of `'number'`: https://github.com/ONSdigital/eq-survey-runner/pull/1953

**Pull request merged**
